install:
  - "bundle install"
script:
  - "bundle exec rake"
os:
  - linux
  - osx
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - jruby
env:
  CODECLIMATE_REPO_TOKEN=e37a93224a40c36fd6a24465c063e7627661921a868a2d1321ad2937d7889de6
notifications:
  email:
    recipients:
      - foss@spritecloud.com
